### ISSUE TITLE
How do I try this out?

### ISSUE THREAD

**Issue by ghost** [KaranAhlawat/tree-sitter-blade#6]
Hey,

Thanks for starting this.

I'm trying to try this out by following these steps for Neovim: https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers

However, When I try the following:

- git clone https://github.com/KaranAhlawat/tree-sitter-blade.git
- cd tree-sitter-blade
- npm ci
- ./node-modules/tree-sitter/tree-sitter generate

I get the following error:

```
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module './tree-sitter-html/grammar'
```

Can you let me know which node version you're using and which steps you follow to get this working?

If you need more info, let me know.

**Comment by KaranAhlawat** [comment]
Hello, thank you for testing out the grammar. Before we get to finding a solution, I should give you a fair and big warning that the grammar most likely won't work well with the syntax highlighting NeoVim treesitter provides. This is mostly due to me not having added any `highlights.scm` files in the grammar yet. Also, the grammar is very incomplete at the moment. The only working thing are echo statements.

I would have gotten around to implementing tags, but sadly I had to put it on hold for a bit as school is taking priority right now.

Still, if you'd like to use the grammar, maybe work on it on your own to create PRs and other stuff, you're most welcome!

Getting back to your problem, that should simply be because I use the `tree-sitter-html` grammar as a git submodule rather than with an an npm package, and a simple `git clone` as in your case doesn't clone the submodules to the best of my knowledge.

Here's how you can clone the repository 
```
git clone --recurse-submodules https://github.com/KaranAhlawat/tree-sitter-blade.git
```

Alternatively, if you already have the cloned repo, you can do the following
```
cd tree-sitter-blade
git submodule update --init --recurse
```

That should deal with it. Try `tree-sitter generate` again and it should work!

**Comment by ghost** [comment]
Thanks for providing steps on how to set this up, tree-sitter generate now works. I'll see whether I can add anything useful through a PR, like the neovim stuff or other blade things.
